### ISSUE TITLE
KeyError: 'WLTW'

### ISSUE THREAD

**Issue by abstractionjackson** [nickmccullum/algorithmic-trading-python#25]
A symbol from the list may need to be updated for the iex sandbox

**Comment by DuyKhangTruong** [comment]
I am also having this problem.

**Comment by dekacypher** [comment]
Read this issue, I've already solved the problem 
[https://github.com/nickmccullum/algorithmic-trading-python/issues/21](url)

**Comment by dekacypher** [comment]
If the link doesn't work, go to Closed Issues and you'll see an issue with the same title.

**Comment by brianivander** [comment]
the WLTW company ticker has changed to WTW 
Read the link: https://www.marketwatch.com/story/willis-towers-watson-changing-ticker-symbol-to-wtw-2022-01-07

Need to update the WLTW in the file sp_500_stocks.csv to WTW. It should fix it.
