### ISSUE TITLE
ImportError: cannot import name 'IEX_CLOUD_API_TOKEN' from 'secrets'

### ISSUE THREAD

**Issue by pragasv** [nickmccullum/algorithmic-trading-python#6]

**Comment by Christianp54** [comment]
pragasv did you end up figuring this out? I am getting a 404 error when trying to run the API call. Thought maybe it could be with importing the Token from secrets.... 


ymbol = 'APPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url)
data.status_code

**Comment by nguyenvinhvinh** [comment]
Do you figure it out also? I got the same problem.

**Comment by XYKeyScore** [comment]
did you?
